<a href="https://colab.research.google.com/github/kmcdonnell2022/Statistics_McDonnell/blob/main/Kyle_McDonnell_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100): #this is setting the range of numbers that will be used 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:
for i in range(5,8): #sets the range between 5 and 8 excluding 8
    print(i)

5
6
7


In [4]:
for i in range(3): #sets range to 0-3 excluding 3 and prints test number in front of it
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [5]:
def square(x): #defining what function will be used and setting its parameters 
    return x**2

In [6]:
square(5) #demonstrates the function

25

In [8]:
square(square(2)) # 2 to the 3rd power but by using the square function

16

In [9]:
square(square(square(2))) #raised to the power of 4 using the  square function 


256

In [10]:
square(123456) #demonstrates square function using big numbers

15241383936

In [12]:
square(square(5)) #further demonstrates function

625

In [14]:
def add_two(x): #creates function for x plus 2 
    return x+2

In [17]:
add_two(5) #demonstrates function 

7

In [18]:
square(add_two(5)) #add two to x (5) then square it

49

### Logical Branching

In [19]:
choice = "apple" #setting the variable to a word 

In [20]:
if choice == "apple": #if you chose appple it will display that you chose apple, if not it will display that you did not choose apple

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange" #settig variable to a differnt word 

In [ ]:
if choice == "apple": #displayed twice

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple"

In [21]:
if choice == "apple": #adding printed sayings to fucntion

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [35]:
choice = input("Please enter your choice (i.e. apple): ") #this gives the abilty to choose apple or orange when prompted 

Please enter your choice (i.e. apple): oranges


In [36]:
choice #displays input choice 

'oranges'

In [38]:
if choice == "apple": #Displays your choice if spelled correctly 

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


#### Coins

In [42]:
import numpy as np #need to include import numpy as np 

In [43]:
np.random.random()  #picks a random number 

0.9201902650132425

In [50]:
np.random.random() > 0.5 #chooses random number, if over 0.5 it will display true or false, cant tell which at this moment

False

In [52]:
def flip_coin(): #assings heads to number > 0.5 and tail to numbers < 0.5
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [54]:
flip_coin() #running the coin flip function 

Heads


### Graphics Output

In [60]:
from IPython.core.display import display, HTML  #importing I python.core.display 

In [61]:
display(HTML('<h1>Hello, world!</h1>')) #displays hello worlds from the Ipython.core.display

In [71]:
def coin(): #sets parameters of range for coin flip to 0-2 excluding 2
  return np.random.randint(2)

In [70]:
coin() #this will display 0 or 1 

1

In [74]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #displays image for heads

In [75]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #links to images for heads and tails 
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [78]:
def show_img(img): #creating function to show the image of the coin (heads or tails) 
  display(HTML('<img src=' + img + '>'))

In [79]:
show_img(heads) #showing heads 

In [80]:
show_img(tails) #showing tails

In [81]:
def flip_coin(): #dedines coin flip function 

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [83]:
flip_coin() #demonstrates function

In [86]:
for i in range(5): #flips 5 coins and displays results 
    flip_coin()

In [84]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [87]:
def shuffle(x): #defines function of shuffle
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [92]:
a = np.arange(52) #assings varibale a to a ragnge of 0-52 excliding 52

In [93]:
shuffle(a) #shuffles range and displays the numbers in a random order

array([ 0, 18, 32, 41, 33, 35,  7, 42, 20, 43, 27, 12, 23, 37, 28, 40,  8,
       36, 24,  4,  5, 31, 34,  3, 50, 39, 48,  9, 45, 14, 38, 49, 30, 51,
       13, 10, 17, 44,  1, 11, 19,  6, 26, 22, 21, 25,  2, 16, 15, 29, 47,
       46])

In [95]:
np.random.permutation(52) #makes a sequence of randoms numbers 0-52 excluding 52

array([31, 28, 13, 22, 32, 15, 41, 42,  6, 18, 47, 29,  3, 34, 23,  8, 19,
       24, 11, 38, 37, 10,  0, 30, 17, 51, 12, 36, 40, 33, 26, 49, 39,  7,
       27, 35, 44,  9, 50, 45,  4,  1, 48,  5, 25, 21, 43,  2, 46, 20, 16,
       14])

### Speed Test

In [98]:
%%timeit 
shuffle(a) #how many times a can suffled 

161 µs ± 2.36 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [99]:
%%timeit
np.random.permutation(52) #random shuffle of sequence

3.53 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [100]:
import numpy as np

In [101]:
np.random.permutation(52) #makes a sequence of randoms numbers 0-52 excluding 52

array([ 0, 29, 42, 15, 33, 19, 23, 46, 51, 18, 26, 36,  2,  7, 48,  8, 24,
       37, 47, 49, 22, 11, 35, 41, 16,  6, 25,  1, 30,  3, 32, 34,  9, 20,
       21, 38, 44, 43, 40, 13, 39, 50, 10, 28,  4,  5, 45, 17, 14, 12, 27,
       31])

In [102]:
cards = np.random.permutation(52) #sets cards to the random permutation 

In [104]:
cards #displays cards at random

array([41, 11,  0, 13, 23, 16, 35, 39,  3,  1,  8, 33, 49, 50, 27, 36,  4,
       46, 44, 22, 24, 17,  5, 12, 40, 42, 38, 29, 37,  7, 43, 21, 34, 20,
       19, 14, 32, 30, 48, 26, 18, 10, 51,  6, 28,  9, 15,  2, 47, 31, 25,
       45])

In [108]:
cards[0] #displays card number you choose

41

In [109]:
cards[1] #displays card number you choose

11

In [110]:
cards[2] #displays card number you choose

0

In [111]:
#thses are the cards thta will be assigned to a number within the array 

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [115]:
np.arange(52).reshape(4,13)  #arranges cards and reshapes them 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [116]:
np.arange(52).reshape(4,13)%13 #arranges cards, reshapes them, and divides into groups of 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [117]:
np.arange(52).reshape(4,13)//13 #arranges cards, reshapes them, and double divides into groups of 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [119]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #defines suits and card numbers
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [121]:
def card_name(card_number): #defines card name and number within the function 
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [122]:
card_name(0) #displays card number and suit of card chosen 

'Ace of Clubs'

In [123]:
card_name(51) #displays card number and suit of card chosen 

'King of Diamonds'

In [125]:
cards = np.random.permutation(52) #sets cards to the random permutation 

In [128]:
top_of_deck         = card_name(cards[0]) #assings names to cards in order
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [129]:
top_of_deck, second_card_in_deck, last_card_in_deck #test the above function 

('Ten of Diamonds', 'Four of Clubs', 'Seven of Hearts')

In [130]:
for i in range(5): #print 5 different cards
    print(card_name(cards[i]))

Ten of Diamonds
Four of Clubs
Three of Spades
Five of Spades
Queen of Hearts


In [131]:
for i in range(15): #print 15 diffent cards
    print(card_name(cards[i]))

Ten of Diamonds
Four of Clubs
Three of Spades
Five of Spades
Queen of Hearts
Queen of Diamonds
Ten of Clubs
Ten of Spades
Three of Hearts
Nine of Clubs
Queen of Clubs
King of Spades
Seven of Clubs
Three of Diamonds
Nine of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [145]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"  #setting variable to url for heads
card_url_tail = ".png" #setting variable to url for tails 

In [132]:
suit = ['k','p','s','l'] #assigns varibale to suits 
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] #sets variable to card

In [134]:
i = np.random.randint(4) #creates variable equal to whole number at random using randint
j = np.random.randint(13)

In [135]:
i,j #picks a random number for variables

(1, 7)

In [136]:
suit[i] #picks random suit for card

'p'

In [137]:
card[j]  #picks random suit for card

'8'

In [141]:
from IPython.core.display import display, HTML

In [142]:
def show_img(img): #displays card image
  display(HTML('<img src=' + img + '>'))

In [148]:
img = card_url_head + suit[i] + card[j] + card_url_tail  #displays image

In [149]:
show_img(img) #image displayed for card

In [156]:
def card_image(card_number): #defines the function to display card image for certain card
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [157]:
card_image(3) #shows image

'k4'

In [154]:
img = card_url_head + card_image(3) + card_url_tail #shows image 

In [158]:
show_img(img) #displays image

In [159]:
for i in range(52): #displays 52 cards and images
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)